/*
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CommandesGet200ResponseInner;
import org.openapitools.client.model.CommandesPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommandesApi
 */
@Disabled
public class CommandesApiTest {

    private final CommandesApi api = new CommandesApi();

    /**
     * Get a list of commands
     *
     * Retrieve information about commandes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void commandesGetTest() throws ApiException {
        List<CommandesGet200ResponseInner> response = api.commandesGet();
        // TODO: test validations
    }

    /**
     * Delete command by ID
     *
     * Remove a specific command.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void commandesIdDeleteTest() throws ApiException {
        Long id = null;
        api.commandesIdDelete(id);
        // TODO: test validations
    }

    /**
     * Get command by ID
     *
     * Retrieve information about a specific command.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void commandesIdGetTest() throws ApiException {
        Long id = null;
        CommandesGet200ResponseInner response = api.commandesIdGet(id);
        // TODO: test validations
    }

    /**
     * Update command by ID
     *
     * Update information about a specific command.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void commandesIdPutTest() throws ApiException {
        Long id = null;
        CommandesPostRequest commandesPostRequest = null;
        api.commandesIdPut(id, commandesPostRequest);
        // TODO: test validations
    }

    /**
     * Create a new command
     *
     * Add a new command to the list.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void commandesPostTest() throws ApiException {
        CommandesPostRequest commandesPostRequest = null;
        api.commandesPost(commandesPostRequest);
        // TODO: test validations
    }

}
